services:
  db:
    image: postgres:latest
    container_name: postgrestest
    environment:
      POSTGRES_USER: myUser
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: myDatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myUser -d myDatabase"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
volumes:
  postgres_data: